# Generated by Django 4.2.8 on 2024-02-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount_incured',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_incured',
            field=models.CharField(max_length=30),
        ),
    ]
