# Generated by Django 4.2.8 on 2024-02-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_expense_amount_incured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='amount_saved',
            field=models.IntegerField(),
        ),
    ]
