# Generated by Django 4.2.8 on 2024-06-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_rename_amount_incured_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user_selection',
            field=models.CharField(choices=[('Dog Training', 'Dog Training'), ('Dog Sales', 'Dog Sales'), ('Equipment Sales', 'Equipment Sales'), ('Kitchen', 'Kitchen'), ('Donnations', 'Donations')], default='Dog Training', max_length=22),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Dog Training', 'Dog Training'), ('Dog Sales', 'Dog Sales'), ('Equipment Sales', 'Equipment Sales'), ('Kitchen', 'Kitchen'), ('Donnations', 'Donations')], default=0, max_length=22),
        ),
    ]
