# Generated by Django 4.2.8 on 2024-07-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_category_user_selection_alter_income_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='comment',
            field=models.CharField(default='', max_length=30),
        ),
    ]
