# Generated by Django 4.2.8 on 2024-07-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_income_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user_selection',
            field=models.CharField(choices=[('Dog Training', 'Dog Training'), ('Dog Sales', 'Dog Sales'), ('Equipment Sales', 'Equipment Sales'), ('Kitchen', 'Kitchen'), ('Donnations', 'Donations'), ('Fresh Juice', 'Fresh Juice')], default='Dog Training', max_length=22),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Dog Training', 'Dog Training'), ('Dog Sales', 'Dog Sales'), ('Equipment Sales', 'Equipment Sales'), ('Kitchen', 'Kitchen'), ('Donnations', 'Donations'), ('Fresh Juice', 'Fresh Juice')], default=0, max_length=22),
        ),
    ]
